#!/bin/bash
set -e

# libstdc++ has to be built in the gcc build directory, otherwise it would
# re-build the whole compiler

GCC_BUILD_DIR="$SHBUILD_ROOT/build/gcc/system-${ARCH}"
cd "${GCC_BUILD_DIR}"
make -j "$PARALLEL_JOBS" all-target-libstdc++-v3 CFLAGS_FOR_TARGET='-g -Os -ffunction-sections -fdata-sections'

