#!/bin/bash
set -e

if [[ "$ARCH" != "x86_64" ]]; then
    exit 0
fi

SRCDIR="$PWD"
cd "$SHBUILD_BUILD_DIR"

make -f "$SRCDIR/Makefile" "CC=$ARCH-zagto-zagtos-gcc" "LD=$ARCH-zagto-zagtos-ld" "AR=$ARCH-zagto-zagtos-ar" "AS=$ARCH-zagto-zagtos-as"

make -f "$SRCDIR/Makefile"


# -j "$PARALLEL_JOBS"
