#!/bin/bash
set -e

function check_toolchain() {
    NAME="$1"
    TARGET="$2"
    NOHEADERS="$3"
    TARGET_CFLAGS="$4"

    TOOLCHAIN_DIR="$SHBUILD_ROOT/out/$ARCH/toolchain/$NAME"
    GCC_BUILD_DIR="$SHBUILD_ROOT/build/$ARCH/gcc/$NAME"
    GCC_SOURCE_DIR="$PWD"

    pushd "$GCC_BUILD_DIR"
    make install-gcc
    make install-target-libgcc
    popd
}

. check-toolchains.sh
